---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-camel-sb-svc
  name: my-camel-sb-svc
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-camel-sb-svc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-camel-sb-svc
    spec:
      containers:
      - image: docker.io/squakez/my-camel-sb-svc:1.0.0
        imagePullPolicy: IfNotPresent
        name: my-camel-sb-svc
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: my-cm
          mountPath: /tmp/app/data
      volumes:
      - name: my-cm
        configMap:
          name: my-cm
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-camel-sb-svc
  name: my-camel-sb-svc
  namespace: default
spec:
  clusterIP: 10.107.124.118
  clusterIPs:
  - 10.107.124.118
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32001
    port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: my-camel-sb-svc
  sessionAffinity: None
  type: NodePort